jobs:
- job: Test
  container:
    image: "linuxbrew/brew"
  steps:
  - script: |
      sudo apt-get update -qq
      sudo apt-get install -qq libboost-dev libsparsehash-dev automake
    displayName: Install C++ modules
  - script: |
      ./autogen.sh
      ./configure
      make
    displayName: Compile ARCS
  - script: |
      sudo HOMEBREW_NO_AUTO_UPDATE=1 /home/linuxbrew/.linuxbrew/bin/brew install python
      sudo /home/linuxbrew/.linuxbrew/bin/pip3 install --upgrade setuptools \
      -U pip --no-cache-dir \
      pylint .
    displayName: Install Python packages
    env:
      HOMEBREW_NO_AUTO_UPDATE: 1
  - script: |
      cd Examples
      pylint long-to-linked-pe makeTSVfile.py
      cd ../
    displayName: Run pylint
  - script: make distcheck
    displayName: Compile ARCS with make distcheck
  - script: |
      curl https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-8 main"
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends clang-format-8
      sudo ln -sf clang-format-8 /usr/bin/clang-format
    displayName: Install clang-format
  - script: make -C Arcs clang-format
    displayName: Run clang-format
- job: Test
  pool:
    vmImage: Ubuntu 16.04
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: "3.7"
      architecture: x64
  - script: |
      curl https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
      sudo apt-add-repository "deb http://apt.llvm.org/xenial/ llvm-toolchain-xenial-11 main"
      sudo apt-get update
      sudo apt-get install -y --no-install-recommends clang-format-11 clang-tidy-11
      sudo ln -s clang-format-11 /usr/bin/clang-format
      sudo ln -s clang-tidy-11 /usr/bin/clang-tidy
    displayName: Install clang-format and clang-tidy
  - script: make -C src all
    displayName: Compile C++ executables
  - script: make -C src lint
    displayName: Run clang-format and clang-tidy

